### PR TITLE
Create workflow to run tests on push & PR

### LINKED ISSUE #14: Create GitHub Actions workflow for running tests automatically

### PR DESCRIPTION
**Pull request by hellovietduc**
Automatically run tests on new pushes or new PRs to master branch.
Closes: #14

### CODE REVIEW

**Comment by trungducc** [comment]
LGTM but do you know why checks are failing?

**Comment by trungducc** [comment]
@vietduc01100001 next time don't forget creating an issue before working on any task.

**Comment by thanks173** [comment]
> LGTM but do you know why checks are failing?

Because there're only README file in the repo, nothing to test.

**Review by thanks173 — APPROVED** [review]

**Comment by hellovietduc** [comment]
I mean to run the tests on code in the PRs, but right now it just runs on the master branch. Will look in to it.

**Comment by hellovietduc** [comment]
Close because GitHub Actions workflow should be set up on forks.

**Pull request closed without merging**
